import { NextResponse } from "next/server";
import { gridCrawler } from "@/lib/crawler/grid-crawler";

export const dynamic = "force-dynamic";

export interface DataSourceItem {
  id: string;
  pillar: string;
  pillarNumber: number;
  name: string;
  provider: string;
  endpointUrl: string;
  format: "REST/JSON" | "GeoJSON" | "ArcGIS REST" | "Parquet/S3" | "T-SQL REST" | "CSV/Raster";
  authRequirement: "None (100% Free / Public Domain)" | "Free API Key (Optional)" | "Open Data License";
  updateCadence: "Real-Time (Continuous)" | "Hourly" | "Daily" | "Monthly" | "Annual / Climatological";
  status: "ONLINE" | "SYNCED" | "POLLING";
  coverage: "Global" | "North America" | "Europe" | "Asia-Pacific";
  recordsIndexed: string;
  description: string;
  docsUrl: string;
}

const DATA_SOURCES_REGISTRY: DataSourceItem[] = [
  // Pillar 1: Data Centers & Cloud Operators
  {
    id: "peeringdb-fac",
    pillar: "Data Centers & Cloud Facilities",
    pillarNumber: 1,
    name: "PeeringDB Global Facility & IXP Registry",
    provider: "PeeringDB Non-Profit",
    endpointUrl: "https://www.peeringdb.com/api/fac",
    format: "REST/JSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Daily",
    status: "SYNCED",
    coverage: "Global",
    recordsIndexed: "6,686 Facilities",
    description: "Authoritative global directory of colocation, hyperscale campuses, cross-connect facilities, and available carriers.",
    docsUrl: "https://docs.peeringdb.com/api_specs/",
  },
  {
    id: "cloudflare-radar",
    pillar: "Data Centers & Cloud Facilities",
    pillarNumber: 1,
    name: "Cloudflare Radar Network & Routing Intelligence",
    provider: "Cloudflare",
    endpointUrl: "https://api.cloudflare.com/client/v4/radar/",
    format: "REST/JSON",
    authRequirement: "Free API Key (Optional)",
    updateCadence: "Real-Time (Continuous)",
    status: "ONLINE",
    coverage: "Global",
    recordsIndexed: "Global ASN Mesh",
    description: "Real-time Internet routing changes, outages, BGP hijack detection, and global autonomous network health.",
    docsUrl: "https://developers.cloudflare.com/radar/",
  },

  // Pillar 2: Power Grid, Plants & Transmission
  {
    id: "us-iso-grid",
    pillar: "Power Grid, Generation & Markets",
    pillarNumber: 2,
    name: "US Regional Transmission Organizations (PJM, ERCOT, CAISO, MISO)",
    provider: "FERC / Regional ISOs",
    endpointUrl: "https://api.pjm.com/api/v1/ / CAISO OASIS / ERCOT MIS",
    format: "REST/JSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Real-Time (Continuous)",
    status: "ONLINE",
    coverage: "North America",
    recordsIndexed: "7 Major RTOs",
    description: "5-minute locational marginal pricing (LMP), real-time fuel dispatch, generation mix, and transmission constraint telemetry.",
    docsUrl: "https://www.ferc.gov/electric-power-markets",
  },
  {
    id: "entsoe-transparency",
    pillar: "Power Grid, Generation & Markets",
    pillarNumber: 2,
    name: "ENTSO-E Transparency Platform",
    provider: "European Network of Transmission System Operators",
    endpointUrl: "https://transparency.entsoe.eu/api",
    format: "REST/JSON",
    authRequirement: "Free API Key (Optional)",
    updateCadence: "Hourly",
    status: "ONLINE",
    coverage: "Europe",
    recordsIndexed: "35 European TSOs",
    description: "Hourly day-ahead electricity prices, cross-border commercial flows, installed capacity, and renewable energy generation across Europe.",
    docsUrl: "https://transparency.entsoe.eu/content/static_html/Static%20content/web%20api/Guide.html",
  },
  {
    id: "eia-open-data",
    pillar: "Power Grid, Generation & Markets",
    pillarNumber: 2,
    name: "US EIA Open Data API v2 (Forms 860, 923 & 930)",
    provider: "US Energy Information Administration",
    endpointUrl: "https://api.eia.gov/v2/electricity/",
    format: "REST/JSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Daily",
    status: "SYNCED",
    coverage: "North America",
    recordsIndexed: "3,450+ Power Plants",
    description: "Comprehensive technical specifications, cooling water intake types, net summer capacity, and hourly balancing authority demands.",
    docsUrl: "https://www.eia.gov/opendata/",
  },

  // Pillar 3: Telecommunications, Fiber & Subsea
  {
    id: "telegeography-cables",
    pillar: "Telecommunications & Dark Fiber",
    pillarNumber: 3,
    name: "TeleGeography Submarine Cable Map Open Dataset",
    provider: "TeleGeography",
    endpointUrl: "https://www.submarinecablemap.com/api/v3/cable/all.json",
    format: "GeoJSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Monthly",
    status: "SYNCED",
    coverage: "Global",
    recordsIndexed: "550+ Subsea Cables",
    description: "Transoceanic fiber paths, cable landing stations, ownership consortia, design capacity (Tbps), and ready-for-service (RFS) dates.",
    docsUrl: "https://github.com/telegeography/www.submarinecablemap.com",
  },
  {
    id: "caida-as-rank",
    pillar: "Telecommunications & Dark Fiber",
    pillarNumber: 3,
    name: "CAIDA AS-Rank Internet Peering Topology",
    provider: "Center for Applied Internet Data Analysis (UC San Diego)",
    endpointUrl: "https://api.asrank.caida.org/v2/graphql",
    format: "REST/JSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Daily",
    status: "ONLINE",
    coverage: "Global",
    recordsIndexed: "74,000+ ASNs",
    description: "Autonomous System customer cones, Tier 1 carrier transit ranking, and peering degree analysis for carrier neutrality scoring.",
    docsUrl: "https://asrank.caida.org/about",
  },
  {
    id: "fra-rail-fiber",
    pillar: "Telecommunications & Dark Fiber",
    pillarNumber: 3,
    name: "US DOT BTS / FRA Rail Network Lines (Dark Fiber Conduits)",
    provider: "US Department of Transportation",
    endpointUrl: "https://geodata.bts.gov/arcgis/rest/services/NTAD/North_American_Rail_Network_Lines/FeatureServer/0/query",
    format: "ArcGIS REST",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Monthly",
    status: "SYNCED",
    coverage: "North America",
    recordsIndexed: "185,000 Miles Rail/Fiber",
    description: "Mainline railroad rights-of-way that house 80%+ of intercity dark fiber conduits (Zayo, Lumen, Bandwidth IG).",
    docsUrl: "https://geodata.bts.gov/",
  },

  // Pillar 4: Seismic Hazards & Active Faults
  {
    id: "usgs-realtime-eq",
    pillar: "Seismic Hazards & Active Faults",
    pillarNumber: 4,
    name: "USGS Real-Time Earthquake GeoJSON Feed",
    provider: "US Geological Survey",
    endpointUrl: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson",
    format: "GeoJSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Real-Time (Continuous)",
    status: "ONLINE",
    coverage: "Global",
    recordsIndexed: "933+ Major Events (M5.0+)",
    description: "Live real-time seismic feeds delivering magnitude, hypocenter depth, modified Mercalli intensity (MMI), and shake map contours.",
    docsUrl: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php",
  },
  {
    id: "usgs-quaternary-faults",
    pillar: "Seismic Hazards & Active Faults",
    pillarNumber: 4,
    name: "USGS Quaternary Faults MapServer",
    provider: "US Geological Survey",
    endpointUrl: "https://earthquake.usgs.gov/arcgis/rest/services/haz/Qfaults/MapServer/21/query",
    format: "ArcGIS REST",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Annual / Climatological",
    status: "SYNCED",
    coverage: "Global",
    recordsIndexed: "12,000+ Fault Segments",
    description: "Active fault traces with slip rate classifications (<0.2 mm/yr to >5 mm/yr) and estimated displacement potential.",
    docsUrl: "https://www.usgs.gov/programs/earthquake-hazards/faults",
  },

  // Pillar 5: Floods, Sea Level Rise & Storm Surge
  {
    id: "fema-nfhl",
    pillar: "Floods & Hydrological Hazards",
    pillarNumber: 5,
    name: "FEMA National Flood Hazard Layer (NFHL) Layer 28",
    provider: "Federal Emergency Management Agency",
    endpointUrl: "https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer/28/query",
    format: "ArcGIS REST",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Monthly",
    status: "ONLINE",
    coverage: "North America",
    recordsIndexed: "100-Yr & 500-Yr Floodplains",
    description: "Official regulatory flood hazard determinations distinguishing Zone A/AE (100-yr riverine), Zone V (coastal surge), and Zone X (minimal risk).",
    docsUrl: "https://hazards.fema.gov/femaportal/wps/portal/NFHLStatusKMZ",
  },
  {
    id: "noaa-slosh-surge",
    pillar: "Floods & Hydrological Hazards",
    pillarNumber: 5,
    name: "NOAA Coastal Inundation & Sea Level Rise Viewer",
    provider: "NOAA Office for Coastal Management",
    endpointUrl: "https://coast.noaa.gov/arcgis/rest/services/dc_slr/",
    format: "ArcGIS REST",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Annual / Climatological",
    status: "SYNCED",
    coverage: "Global",
    recordsIndexed: "1ft to 10ft Inundation Contours",
    description: "High-resolution coastal inundation projections and SLOSH model maximum envelope of water (MEOW) for Category 1-5 hurricanes.",
    docsUrl: "https://coast.noaa.gov/digitalcoast/tools/slr.html",
  },

  // Pillar 6: Severe Storms & Disasters
  {
    id: "noaa-spc-svrgis",
    pillar: "Severe Weather & Climate Disasters",
    pillarNumber: 6,
    name: "NOAA Storm Prediction Center (SPC) SVRGIS",
    provider: "NOAA National Weather Service",
    endpointUrl: "https://www.spc.noaa.gov/gis/svrgis/",
    format: "CSV/Raster",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Annual / Climatological",
    status: "SYNCED",
    coverage: "North America",
    recordsIndexed: "460+ Severe Storm Events",
    description: "Historical geometries and touchdown tracks for all verified tornadoes (EF0-EF5), damaging hail, and straight-line winds (1950-2024).",
    docsUrl: "https://www.spc.noaa.gov/wcm/",
  },
  {
    id: "gdacs-live-feed",
    pillar: "Severe Weather & Climate Disasters",
    pillarNumber: 6,
    name: "GDACS Global Disaster Alert & Coordination System",
    provider: "United Nations / European Commission",
    endpointUrl: "https://www.gdacs.org/xml/gdacs.geojson",
    format: "GeoJSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Real-Time (Continuous)",
    status: "ONLINE",
    coverage: "Global",
    recordsIndexed: "Live Red/Orange Alerts",
    description: "Multi-hazard international early warning system for active tropical cyclones, earthquakes, tsunamis, floods, and volcano eruptions.",
    docsUrl: "https://www.gdacs.org/",
  },

  // Pillar 7: Ambient Climate & Free Cooling
  {
    id: "nasa-power-api",
    pillar: "Ambient Climate & Cooling Physics",
    pillarNumber: 7,
    name: "NASA POWER Global Solar & Meteorological API",
    provider: "NASA Langley Research Center",
    endpointUrl: "https://power.larc.nasa.gov/api/temporal/hourly/point",
    format: "REST/JSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Daily",
    status: "SYNCED",
    coverage: "Global",
    recordsIndexed: "Hourly Wet-Bulb & Dew Point",
    description: "Worldwide 0.5-degree grid resolution providing hourly dry-bulb (T2M), relative humidity, and thermodynamic wet-bulb for PUE economizer calculation.",
    docsUrl: "https://power.larc.nasa.gov/docs/",
  },
  {
    id: "open-meteo-climate",
    pillar: "Ambient Climate & Cooling Physics",
    pillarNumber: 7,
    name: "Open-Meteo Historical Climate & Forecast Archive",
    provider: "Open-Meteo Open-Source Weather",
    endpointUrl: "https://archive-api.open-meteo.com/v1/archive",
    format: "REST/JSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Hourly",
    status: "ONLINE",
    coverage: "Global",
    recordsIndexed: "1950–Present Climate Profiles",
    description: "High-accuracy reanalysis downscaled from ERA5 and national weather models for free-cooling hours estimation.",
    docsUrl: "https://open-meteo.com/en/docs",
  },

  // Pillar 8: Water Resources & Wastewater
  {
    id: "wri-aqueduct",
    pillar: "Water Resources & Wastewater",
    pillarNumber: 8,
    name: "WRI Aqueduct 4.0 Water Risk Atlas",
    provider: "World Resources Institute",
    endpointUrl: "https://www.wri.org/data/aqueduct-global-maps-40-data",
    format: "GeoJSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Annual / Climatological",
    status: "SYNCED",
    coverage: "Global",
    recordsIndexed: "HydroBASINS Level 6 Watersheds",
    description: "Global assessment of baseline water stress (withdrawals vs supply), interannual variability, and groundwater table depletion rates.",
    docsUrl: "https://www.wri.org/aqueduct",
  },
  {
    id: "epa-echo-npdes",
    pillar: "Water Resources & Wastewater",
    pillarNumber: 8,
    name: "EPA ECHO Clean Water Act (NPDES) Permitted Facilities",
    provider: "US Environmental Protection Agency",
    endpointUrl: "https://echodata.epa.gov/echo/cwa_rest_services.get_facilities",
    format: "REST/JSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Monthly",
    status: "ONLINE",
    coverage: "North America",
    recordsIndexed: "POTW Wastewater Outfalls",
    description: "Municipal wastewater treatment plant design capacities (MGD), average discharge volumes, and cooling tower blowdown reception headroom.",
    docsUrl: "https://echo.epa.gov/tools/web-services",
  },

  // Pillar 9: Soil, Bedrock & Topography
  {
    id: "usda-ssurgo-sda",
    pillar: "Soil Mechanics & Topography",
    pillarNumber: 9,
    name: "USDA NRCS Soil Data Access (SSURGO T-SQL Spatial REST)",
    provider: "USDA Natural Resources Conservation Service",
    endpointUrl: "https://sdmdataaccess.sc.egov.usda.gov/tabular/post.rest",
    format: "T-SQL REST",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Annual / Climatological",
    status: "SYNCED",
    coverage: "North America",
    recordsIndexed: "30M+ Soil Polygons",
    description: "Soil bearing capacity, depth to lithic bedrock contact, steel/concrete corrosion ratings, and liquefaction vulnerability.",
    docsUrl: "https://sdmdataaccess.nrcs.usda.gov/",
  },
  {
    id: "usgs-3dep-elevation",
    pillar: "Soil Mechanics & Topography",
    pillarNumber: 9,
    name: "USGS 3DEP Elevation Point Query Service (EPQS)",
    provider: "US Geological Survey",
    endpointUrl: "https://epqs.nationalmap.gov/v1/rest/point",
    format: "REST/JSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Annual / Climatological",
    status: "ONLINE",
    coverage: "Global",
    recordsIndexed: "Sub-Meter LiDAR Contours",
    description: "Bare-earth digital elevation model (DEM) for parcel slope grading suitability (<3% optimal for cut-and-fill minimization).",
    docsUrl: "https://apps.nationalmap.gov/epqs/",
  },

  // Pillar 10: Aviation, Pipelines & Zoning
  {
    id: "faa-part77-airspace",
    pillar: "Aviation, Pipelines & Industrial Hazards",
    pillarNumber: 10,
    name: "FAA Aeronautical GIS (Part 77 Imaginary Surfaces)",
    provider: "Federal Aviation Administration",
    endpointUrl: "https://adds-faa.opendata.arcgis.com/",
    format: "ArcGIS REST",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Monthly",
    status: "SYNCED",
    coverage: "North America",
    recordsIndexed: "Commercial Flight Corridors",
    description: "Runway alignment centerlines, airport approach cones (34:1, 40:1 slopes), and height clearance limits.",
    docsUrl: "https://adds-faa.opendata.arcgis.com/",
  },
  {
    id: "eia-gas-pipelines",
    pillar: "Aviation, Pipelines & Industrial Hazards",
    pillarNumber: 10,
    name: "EIA / HIFLD Natural Gas Transmission Pipelines",
    provider: "US Energy Information Administration / DHS",
    endpointUrl: "https://services7.arcgis.com/FGr1D95X0LlFrvkW/arcgis/rest/services/Natural_Gas_Pipelines/FeatureServer/0/query",
    format: "ArcGIS REST",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Annual / Climatological",
    status: "SYNCED",
    coverage: "North America",
    recordsIndexed: "300,000+ Pipeline Miles",
    description: "High-pressure interstate natural gas pipeline routes with 1,500 ft Potential Impact Radius (PIR) blast buffer envelopes.",
    docsUrl: "https://hifld-geoplatform.opendata.arcgis.com/",
  },
  {
    id: "epa-tri-rmp",
    pillar: "Aviation, Pipelines & Industrial Hazards",
    pillarNumber: 10,
    name: "EPA Toxic Release Inventory (TRI) & RMP Facilities",
    provider: "US Environmental Protection Agency",
    endpointUrl: "https://enviro.epa.gov/enviro/efservice/TRI_FACILITY/",
    format: "REST/JSON",
    authRequirement: "None (100% Free / Public Domain)",
    updateCadence: "Annual / Climatological",
    status: "ONLINE",
    coverage: "North America",
    recordsIndexed: "21,000+ Chemical Facilities",
    description: "Major hazardous chemical storage and toxic inhalation hazard (TIH) facilities requiring 3-mile industrial setback buffers.",
    docsUrl: "https://www.epa.gov/enviro/tri-search",
  },
];

export async function GET() {
  try {
    const auditHistory = gridCrawler.getAuditHistory();
    const latestAudit = auditHistory[0] || null;

    return NextResponse.json({
      success: true,
      totalPillars: 10,
      totalSourcesMonitored: DATA_SOURCES_REGISTRY.length,
      allFreeOpenSource: true,
      latestAudit,
      stats: {
        dataCentersCount: 6686,
        powerPlantsCount: 3450,
        substationsCount: 602,
        historicalEarthquakesCount: 933,
        historicalStormsCount: 460,
        climateNormalsCount: 13,
      },
      sources: DATA_SOURCES_REGISTRY,
      cronSchedules: [
        {
          name: "Vercel Continuous Cron Crawler",
          schedule: "0 */6 * * * (Every 6 Hours)",
          target: "/api/cron/crawler",
          purpose: "Refreshes live USGS earthquakes, GDACS disaster alerts, and audits data center links",
        },
        {
          name: "GitHub Actions Infrastructure Workflow",
          schedule: "0 2 * * * (Daily at 02:00 UTC)",
          target: ".github/workflows/infrastructure-crawler.yml",
          purpose: "Performs full global landmass calibration and dark fiber conduit alignment",
        },
      ],
      timestamp: new Date().toISOString(),
    });
  } catch (err: any) {
    return NextResponse.json(
      { success: false, error: err.message },
      { status: 500 }
    );
  }
}
